### ISSUE TITLE
Support one to many relationships

### ISSUE THREAD

**Issue by jdkandersson** [jdkandersson/OpenAlchemy#16]
As a user I want to define one to many relationships in the OpenAPI specification so that I can use them in my SQLAlchemy models.

**Comment by Shihta** [comment]
Does this mean to support array?

**Comment by jdkandersson** [comment]
Yes, it would, for example, allow for:
```yaml
Schemas:
  Employee:
    ...
  Division:
    ...
    properties:
      ...
      employees:
        type: array
        items:
          "$ref": "#/.../Employee"
```
Which would construct a one to many relationship between division and employee. Is that what you would expect to happen? Are you looking for any other kind of array support?
